'use strict'
const assert=require('assert'),fs=require('fs'),path=require('path')
const root=path.join(__dirname,'..')
const board=fs.readFileSync(path.join(root,'app/crm/schedule-board/page.tsx'),'utf8')
const dialog=fs.readFileSync(path.join(root,'components/crm/booking-dialog.tsx'),'utf8')
const portal=fs.readFileSync(path.join(root,'app/owner-schedule/[token]/page.tsx'),'utf8')
assert.match(board,/AV_NOTIFICATION_TTL_MS = 10_000/)
assert.match(board,/\[\.\.\.fresh, \.\.\.prev\]/)
assert.match(dialog,/Send booking request/)
assert.match(dialog,/Justify client and request once more/)
assert.match(portal,/Back-to-back request/)
assert.match(portal,/Mark my times/)
assert.match(portal,/\[20,10\]/)
console.log('booking request UI: 7 checks passed')
