'use strict'
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const board = fs.readFileSync(path.join(root, 'app/crm/schedule-board/page.tsx'), 'utf8')
const market = fs.readFileSync(path.join(root, 'public/link-marketplace/marketplace.js'), 'utf8')

assert.match(board, /cutoff\.setUTCMonth\(cutoff\.getUTCMonth\(\) \+ 3\)/)
assert.match(board, /data-future-lock=/)
assert.match(board, /Owner recheck · every 8 weeks/)
assert.match(board, /data-future-override=/)
assert.match(board, /disabled=\{futureLocked && !isAdmin\}/)
assert.match(market, /function isFarFutureProperty/)
assert.match(market, /Enquiries and booking actions open when it enters the next three months/)
assert.match(market, /disabled aria-disabled="true"/)
console.log('future property UI lock: ok')
