'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Check, EyeOff, LocateFixed, MapPin, RefreshCw, Search } from 'lucide-react'
import { crmFetch, crmJson } from '@/lib/crm/api'

type Kind = { key: string; pillars: string[] }
type Marker = { id: number; kind: string; name: string; latitude: number; longitude: number; source: string; status: 'suggested'|'approved'|'hidden'; address: string; notes: string; googlePlaceId: string|null; googleTypes: string[]; nexusPillars: string[]; signalRole: 'anchor'|'density_signal'; confidence: number; quality: Record<string, unknown>; publicVisible: boolean }
type Locality = { id:number; label:string; coordinates:[number,number]|null }
const labels: Record<string,string> = { workplace:'Workplaces',beach:'Beaches',swimming_spot:'Swimming spots',sport:'Sports',outdoor_gym:'Outdoor gyms',park:'Parks',restaurant:'Restaurants',cafe:'Cafés',nightlife:'Bars & nightlife',grocery:'Groceries',healthcare:'Healthcare',education:'Education',worship:'Worship',culture:'Culture',transit:'Transit' }
const googleSearch: Record<string,{keyword:string;type?:string}> = {
  workplace:{keyword:'major company office'},beach:{keyword:'beach'},swimming_spot:{keyword:'swimming spot'},sport:{keyword:'sports club'},outdoor_gym:{keyword:'outdoor gym'},park:{keyword:'park',type:'park'},restaurant:{keyword:'restaurant',type:'restaurant'},cafe:{keyword:'cafe',type:'cafe'},nightlife:{keyword:'bar',type:'bar'},grocery:{keyword:'supermarket',type:'supermarket'},healthcare:{keyword:'hospital clinic'},education:{keyword:'school university'},worship:{keyword:'church mosque place of worship'},culture:{keyword:'museum gallery theatre'},transit:{keyword:'bus station ferry terminal'}
}
const field='w-full rounded-lg border border-white/15 bg-[#0f1521] px-3 py-2.5 text-sm text-[#edeae1] focus:outline-none focus:ring-2 focus:ring-[#b8953f]'
const btn='inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-sm disabled:opacity-50'
const colour=(kind:string)=>kind==='workplace'?'#7c8da8':['beach','swimming_spot'].includes(kind)?'#4cc9f0':['sport','outdoor_gym','park'].includes(kind)?'#66c58a':['restaurant','cafe','nightlife'].includes(kind)?'#efad63':'#b8953f'

export function NexusPlaceEditor(){
  const target=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),pins=useRef<any[]>([]),draftPin=useRef<any>(null)
  const [markers,setMarkers]=useState<Marker[]>([]),[kinds,setKinds]=useState<Kind[]>([]),[kind,setKind]=useState('sport'),[status,setStatus]=useState('active')
  const [localities,setLocalities]=useState<Locality[]>([]),[workplaceQuery,setWorkplaceQuery]=useState(''),[predictions,setPredictions]=useState<any[]>([])
  const [selected,setSelected]=useState<Marker|null>(null),[manual,setManual]=useState(false),[draft,setDraft]=useState({name:'',notes:'',latitude:0,longitude:0})
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false)
  const load=useCallback(async()=>{try{const data=await crmFetch(`nexus/place-markers?status=${status}`);setMarkers(data.markers||[]);setKinds(data.kinds||[])}catch(e){setError(e instanceof Error?e.message:'Could not load place intelligence.')}},[status])
  useEffect(()=>{load()},[load])
  useEffect(()=>{crmFetch('nexus/localities').then(data=>setLocalities(data.localities||[])).catch(()=>{})},[])
  useEffect(()=>{let attempts=0;const detect=()=>{if((window as any).google?.maps?.Map){setReady(true);return true}return ++attempts>60};if(detect())return;const timer=setInterval(()=>{if(detect())clearInterval(timer)},250);return()=>clearInterval(timer)},[])
  useEffect(()=>{if(!ready||!target.current||mapRef.current)return;const g=(window as any).google;const map=new g.maps.Map(target.current,{center:{lat:35.91,lng:14.43},zoom:11,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,gestureHandling:'cooperative',clickableIcons:false});mapRef.current=map;const listener=map.addListener('click',(event:any)=>{if(!manual||!event.latLng)return;const latitude=event.latLng.lat(),longitude=event.latLng.lng();setDraft(v=>({...v,latitude,longitude}));draftPin.current?.setMap(null);draftPin.current=new g.maps.Marker({map,position:{lat:latitude,lng:longitude},title:'New internal Nexus marker'})});return()=>{g.maps.event.removeListener(listener);mapRef.current=null}},[ready,manual])
  useEffect(()=>{const g=(window as any).google,map=mapRef.current;if(!g||!map)return;pins.current.forEach(pin=>pin.setMap(null));pins.current=markers.filter(m=>m.status!=='hidden').map(item=>{const pin=new g.maps.Marker({map,position:{lat:item.latitude,lng:item.longitude},title:item.name,opacity:item.status==='suggested'?.58:1,icon:{path:g.maps.SymbolPath.CIRCLE,fillColor:colour(item.kind),fillOpacity:1,strokeColor:'#101722',strokeWeight:2,scale:item.status==='approved'?7:5}});pin.addListener('click',()=>setSelected(item));return pin});return()=>{pins.current.forEach(pin=>pin.setMap(null));pins.current=[]}},[markers,ready])
  const visible=useMemo(()=>markers.filter(m=>kind==='all'||m.kind===kind),[markers,kind])
  const stats=useMemo(()=>({approved:markers.filter(m=>m.status==='approved').length,suggested:markers.filter(m=>m.status==='suggested').length,density:markers.filter(m=>m.signalRole==='density_signal').length}),[markers])
  useEffect(()=>{if(kind!=='workplace'||workplaceQuery.trim().length<2||!ready){setPredictions([]);return}const timer=setTimeout(async()=>{const g=(window as any).google;try{if(g.maps.importLibrary)await g.maps.importLibrary('places');new g.maps.places.AutocompleteService().getPlacePredictions({input:workplaceQuery,componentRestrictions:{country:'mt'},types:['establishment']},(items:any[])=>setPredictions((items||[]).slice(0,6)))}catch{setPredictions([])}},220);return()=>clearTimeout(timer)},[workplaceQuery,kind,ready])
  async function scan(){const g=(window as any).google,map=mapRef.current,query=googleSearch[kind];if(!g||!map||!query)return;setBusy(true);setError('');setMessage('Searching Google Places in this map view…');try{if(g.maps.importLibrary)await g.maps.importLibrary('places');const service=new g.maps.places.PlacesService(map);const results:any[]=await new Promise((resolve,reject)=>service.nearbySearch({bounds:map.getBounds(),keyword:query.keyword,...(query.type?{type:query.type}:{})},(items:any[],code:string)=>code===g.maps.places.PlacesServiceStatus.OK?resolve(items||[]):code===g.maps.places.PlacesServiceStatus.ZERO_RESULTS?resolve([]):reject(new Error(`Google Places returned ${code}.`))));const limit=['restaurant','cafe','nightlife','workplace'].includes(kind)?12:20;const chosen=results.sort((a,b)=>(Number(b.rating||0)*Math.log10(Number(b.user_ratings_total||0)+10))-(Number(a.rating||0)*Math.log10(Number(a.user_ratings_total||0)+10))).slice(0,limit);if(!chosen.length){setMessage('No candidates found in this view.');return}await crmJson('nexus/place-markers','POST',{markers:chosen.map(place=>({kind,name:place.name,latitude:place.geometry.location.lat(),longitude:place.geometry.location.lng(),source:'google',googlePlaceId:place.place_id,address:place.vicinity||'',googleTypes:place.types||[],quality:{rating:place.rating??null,userRatingCount:place.user_ratings_total??null,priceLevel:place.price_level??null,businessStatus:place.business_status??null,openNow:place.opening_hours?.open_now??null}}))});setMessage(`${chosen.length} Google candidates saved for review. ${['restaurant','cafe','nightlife'].includes(kind)?'They act as area-density signals.':''}`);await load()}catch(e){setError(e instanceof Error?e.message:'Google scan failed.')}finally{setBusy(false)}}
  async function saveManual(){if(!draft.name.trim()||!draft.latitude||!draft.longitude)return;setBusy(true);setError('');try{await crmJson('nexus/place-markers','POST',{kind,name:draft.name,notes:draft.notes,latitude:draft.latitude,longitude:draft.longitude,source:'manual'});setDraft({name:'',notes:'',latitude:0,longitude:0});draftPin.current?.setMap(null);setManual(false);setMessage('Manual place approved and stored internally.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not save marker.')}finally{setBusy(false)}}
  async function chooseWorkplace(prediction:any){const g=(window as any).google,map=mapRef.current;if(!g||!map)return;setBusy(true);setError('');try{const place:any=await new Promise((resolve,reject)=>new g.maps.places.PlacesService(map).getDetails({placeId:prediction.place_id,fields:['place_id','name','geometry','formatted_address','types','rating','user_ratings_total','business_status','opening_hours']},(item:any,code:string)=>code===g.maps.places.PlacesServiceStatus.OK?resolve(item):reject(new Error(`Google Places returned ${code}.`))));await crmJson('nexus/place-markers','POST',{kind:'workplace',name:place.name,latitude:place.geometry.location.lat(),longitude:place.geometry.location.lng(),source:'google',googlePlaceId:place.place_id,address:place.formatted_address||'',googleTypes:place.types||[],quality:{rating:place.rating??null,userRatingCount:place.user_ratings_total??null,businessStatus:place.business_status??null}});map.panTo(place.geometry.location);map.setZoom(15);setWorkplaceQuery('');setPredictions([]);setMessage(`${place.name} soft-marked as an internal workplace candidate.`);await load()}catch(e){setError(e instanceof Error?e.message:'Could not add workplace.')}finally{setBusy(false)}}
  async function update(item:Marker,patch:Record<string,unknown>){setBusy(true);setError('');try{const result=await crmJson(`nexus/place-markers/${item.id}`,'PATCH',patch);setSelected(result.marker);setMessage(patch.status==='approved'?'Place approved.':'Place updated.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not update marker.')}finally{setBusy(false)}}
  return <div className="flex min-h-0 flex-1 flex-col overflow-y-auto p-5 md:p-7">
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Approved anchors" value={stats.approved}/><Metric label="Google suggestions" value={stats.suggested}/><Metric label="Density signals" value={stats.density}/></div>
    <div className="mt-5 flex flex-wrap items-end gap-3"><label className="min-w-52 flex-1 text-xs text-[#adb5c6]">Place layer<select className={`${field} mt-1`} value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(item=><option key={item.key} value={item.key}>{labels[item.key]||item.key} · {item.pillars.join(' + ')}</option>)}</select></label><label className="min-w-48 text-xs text-[#adb5c6]">Locality / scan area<select className={`${field} mt-1`} defaultValue="" onChange={e=>{const place=localities.find(p=>p.id===Number(e.target.value));if(place?.coordinates&&mapRef.current){mapRef.current.panTo({lat:place.coordinates[1],lng:place.coordinates[0]});mapRef.current.setZoom(14)}}}><option value="">Current map view</option>{localities.filter(p=>p.coordinates).map(place=><option key={place.id} value={place.id}>{place.label}</option>)}</select></label><label className="text-xs text-[#adb5c6]">Review state<select className={`${field} mt-1`} value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="suggested">Suggested</option><option value="approved">Approved</option><option value="all">All incl. hidden</option></select></label><button className={`${btn} bg-[#b8953f] font-semibold text-[#151c2c]`} disabled={busy||!googleSearch[kind]} onClick={scan}><Search size={15}/>Scan visible map</button><button className={btn} onClick={()=>setManual(v=>!v)}><MapPin size={15}/>{manual?'Cancel pin':'Add manual place'}</button><button className={btn} onClick={load} aria-label="Refresh"><RefreshCw size={15}/></button></div>
    {kind==='workplace'&&<div className="relative mt-3 max-w-xl"><label className="text-xs text-[#adb5c6]">Find a major workplace<input className={`${field} mt-1`} value={workplaceQuery} onChange={e=>setWorkplaceQuery(e.target.value)} placeholder="Start typing Betsson, Kindred, Deloitte…"/></label>{predictions.length>0&&<div className="absolute z-20 mt-1 w-full overflow-hidden rounded-lg border border-white/15 bg-[#101722] shadow-2xl">{predictions.map(item=><button key={item.place_id} className="block w-full border-b border-white/10 px-3 py-2 text-left text-sm last:border-0 hover:bg-white/5" onClick={()=>chooseWorkplace(item)}><strong>{item.structured_formatting?.main_text||item.description}</strong><span className="block text-xs text-[#adb5c6]">{item.structured_formatting?.secondary_text||''}</span></button>)}</div>}</div>}
    <p className="mt-3 text-xs leading-5 text-[#adb5c6]">Google scans only the visible area and keeps a curated sample. Restaurant, café and nightlife points are density signals. Workplaces and every new marker stay internal and invisible on NexusLink.</p>
    <div className="mt-4 grid min-h-[520px] gap-4 lg:grid-cols-[1fr_320px]"><div ref={target} className="min-h-[520px] rounded-xl bg-[#0f1521]" aria-label="Nexus Places Intelligence map"/><aside className="rounded-xl border border-white/10 bg-[#0f1521] p-4">
      {manual?<div className="space-y-3"><h3 className="font-semibold">New manual {labels[kind]||kind}</h3><p className="text-xs text-[#adb5c6]">Tap the exact point on the map. Use Swimming spots for places that are not public beaches.</p><input className={field} placeholder="Place name" value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value}))}/><textarea className={field} rows={4} placeholder="Quality notes, access, atmosphere…" value={draft.notes} onChange={e=>setDraft(v=>({...v,notes:e.target.value}))}/><p className="text-xs text-[#adb5c6]">{draft.latitude?`${draft.latitude.toFixed(6)}, ${draft.longitude.toFixed(6)}`:'No point selected yet.'}</p><button className={`${btn} w-full bg-[#b8953f] font-semibold text-[#151c2c]`} disabled={busy||!draft.name.trim()||!draft.latitude} onClick={saveManual}><Check size={15}/>Save approved marker</button></div>:selected?<div className="space-y-3"><span className="text-xs uppercase tracking-wide text-[#b8953f]">{labels[selected.kind]||selected.kind} · {selected.signalRole.replace('_',' ')}</span><h3 className="text-xl font-semibold">{selected.name}</h3><p className="text-sm text-[#adb5c6]">{selected.address||'No public address'}<br/>{selected.latitude.toFixed(5)}, {selected.longitude.toFixed(5)}</p><div className="flex flex-wrap gap-2">{selected.nexusPillars.map(p=><span key={p} className="rounded-full border border-white/15 px-2 py-1 text-xs">{p}</span>)}</div><Quality quality={selected.quality}/>{selected.notes&&<p className="text-sm">{selected.notes}</p>}<p className="text-xs text-[#adb5c6]">Source: {selected.source} · confidence {Math.round(selected.confidence*100)}% · public pin off</p>{selected.status==='suggested'&&<button className={`${btn} w-full bg-emerald-500/15 text-emerald-200`} disabled={busy} onClick={()=>update(selected,{status:'approved'})}><Check size={15}/>Approve place</button>}<button className={`${btn} w-full`} disabled={busy} onClick={()=>update(selected,{status:'hidden'})}><EyeOff size={15}/>Hide marker</button></div>:<div className="flex h-full min-h-64 flex-col items-center justify-center text-center text-[#adb5c6]"><LocateFixed size={28}/><p className="mt-3">Choose a marker to review its quality data.</p><p className="mt-2 text-xs">{visible.length} markers in this layer</p></div>}
    </aside></div>{message&&<p className="mt-4 rounded-lg bg-emerald-500/10 p-3 text-sm text-emerald-200">{message}</p>}{error&&<p role="alert" className="mt-4 rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
  </div>
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-white/10 bg-[#0f1521] p-4"><strong className="text-2xl">{value}</strong><span className="mt-1 block text-xs text-[#adb5c6]">{label}</span></div>}
function Quality({quality}:{quality:Record<string,unknown>}){const rows=[['Rating',quality.rating],['Reviews',quality.userRatingCount],['Price level',quality.priceLevel],['Business',quality.businessStatus]].filter(([,value])=>value!==null&&value!==undefined);return rows.length?<dl className="grid grid-cols-2 gap-2">{rows.map(([label,value])=><div key={String(label)} className="rounded-lg border border-white/10 p-2"><dt className="text-[10px] text-[#adb5c6]">{String(label)}</dt><dd className="text-sm">{String(value)}</dd></div>)}</dl>:<p className="text-xs text-[#adb5c6]">Quality details can be added during review.</p>}
