import { Property, Agent, RegionInfo, NavItem } from './types'

export const navItems: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Letting', href: '/letting', accentColor: 'accent-letting' },
  { label: 'Aesthetics', href: '/aesthetics', accentColor: 'accent-aesthetics' },
  { label: 'Commercial', href: '/commercial', accentColor: 'accent-commercial' },
  { label: 'Sales', href: '/sales', accentColor: 'accent-sales' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
]

export const languages = [
  { code: 'en', label: 'EN' },
  { code: 'de', label: 'DE' },
  { code: 'ar', label: 'AR' },
  { code: 'zh', label: 'ZH' },
  { code: 'it', label: 'IT' },
  { code: 'fr', label: 'FR' },
  { code: 'es', label: 'ES' },
  { code: 'ko', label: 'KO' },
  { code: 'uk', label: '🇺🇦' },
]

// All Malta villages/locations
export const maltaLocations = [
  "St. Julians", "Swieqi", "Naxxar", "Sliema", "Paceville", "Ta' Xbiex", "Gzira",
  "San Gwann", "Tigne", "Qawra", "Pembroke", "Bugibba", "Ta' l-ibragg", "Madliena",
  "St. Paul's Bay", "Msida", "Valletta", "Pieta", "Birkirkara", "San Pawl", "Balzan",
  "Attard", "Mosta", "Iklin", "Lija", "Xemxija", "Mellieha", "Fgura", "Bahar ic-Caghaq",
  "Bahrija", "Bidnija", "Birgu", "Birguma", "Birzebbuga", "Bormla", "Burmarrad",
  "Dingli", "Floriana", "Fleur-de-lys", "Ghadira", "Ghajn Tuffieha", "Gharghur",
  "Ghaxaq", "Gudja", "Gwardamanga", "Hal Far", "Hal Farrug", "Hamrun", "Imqabba",
  "Imtarfa", "Isla", "Kappara", "Kalkara", "Kirkop", "Luqa", "Maghtab", "Manikata",
  "Marsa", "Marsaskala", "Marsaxlokk", "Mdina", "Mgarr", "Mriehel", "Mtahleb",
  "Paola", "Qajjenza", "Qormi", "Qrendi", "Rabat", "Safi", "Salina", "Santa Lucia",
  "Santa Venera", "Siggiewi", "Swatar", "Tarxien", "Wardija", "Xghajra", "Zabbar",
  "Zebbug", "Zurrieq", "Zejtun", "Vittoriosa",
  // Gozo locations
  "Gozo", "Gozo - Rabat", "Gozo - Fontana", "Gozo - Gharb", "Gozo - Ghasri",
  "Gozo - Kercem", "Gozo - Munxar", "Gozo - Nadur", "Gozo - Qala", "Gozo - San Lawrenz",
  "Gozo - Sannat", "Gozo - Xaghra", "Gozo - Xewkija", "Gozo - Zebbug", "Gozo - Xlendi",
]

// Property types from screenshot
export const propertyTypes = [
  "Apartments",
  "Block",
  "Bungalows",
  "Detached Villa",
  "Duplex Penthouse",
  "Farmhouses",
  "House of Character",
  "Maisonettes",
  "Palace/Castle/Manor",
  "Penthouses",
  "Semi Detached Villa",
  "Studio Apartments",
  "Studio Maisonette",
  "Studio Penthouse",
  "Terraced Houses",
  "Top Floor Apartment",
  "Townhouses",
]

export const bedroomOptions = ['Studio', '1', '2', '3', '4', '5+']

export const regions: RegionInfo[] = [
  {
    id: 'Central East',
    name: 'Central East',
    description: 'The heart of Malta\'s upscale living, featuring prestigious neighborhoods with stunning sea views and modern amenities.',
    advantages: ['Prime location', 'Sea views', 'Vibrant nightlife', 'High-end restaurants', 'Beach access'],
    disadvantages: ['Higher prices', 'Traffic congestion', 'Tourist crowds in summer'],
    priceRange: '€1,500 - €8,000/month',
    typicalProperties: ['Luxury apartments', 'Penthouses', 'Seafront properties'],
    areas: ['Madliena', 'Swieqi', 'Pembroke', 'St Julian\'s', 'Sliema'],
  },
  {
    id: 'Central West',
    name: 'Central West',
    description: 'A blend of traditional Maltese charm and modern convenience, offering excellent value and authentic local experiences.',
    advantages: ['Central location', 'Good value', 'Local character', 'University proximity'],
    disadvantages: ['Less scenic', 'Older buildings', 'Limited parking'],
    priceRange: '€800 - €2,500/month',
    typicalProperties: ['Traditional apartments', 'Maisonettes', 'Townhouses'],
    areas: ['Gzira', 'Hamrun', 'Pieta', 'Msida', 'Birkirkara', 'Qormi'],
  },
  {
    id: 'Central Surroundings',
    name: 'Central Surroundings',
    description: 'Peaceful residential areas offering a perfect balance between accessibility and tranquility.',
    advantages: ['Quieter environment', 'Family-friendly', 'Good schools', 'More space'],
    disadvantages: ['Further from coast', 'Limited nightlife', 'Car recommended'],
    priceRange: '€900 - €3,000/month',
    typicalProperties: ['Villas', 'Semi-detached houses', 'Family apartments'],
    areas: ['Mosta', 'Naxxar', 'Attard', 'Balzan', 'Lija'],
  },
  {
    id: 'North',
    name: 'North',
    description: 'Malta\'s scenic north offers beaches, nature reserves, and a more relaxed pace of life.',
    advantages: ['Beautiful beaches', 'Nature access', 'Less crowded', 'Affordable'],
    disadvantages: ['Distance to capital', 'Limited public transport', 'Seasonal tourism'],
    priceRange: '€700 - €2,500/month',
    typicalProperties: ['Beach apartments', 'Farmhouses', 'Traditional homes'],
    areas: ['Mellieha', 'St Paul\'s Bay', 'Bugibba', 'Qawra'],
  },
  {
    id: 'South',
    name: 'South',
    description: 'Traditional Maltese villages with authentic character, excellent for those seeking genuine local life.',
    advantages: ['Authentic culture', 'Affordable', 'Strong community', 'Historic sites'],
    disadvantages: ['Further from business centers', 'Limited international amenities'],
    priceRange: '€600 - €1,800/month',
    typicalProperties: ['Traditional houses', 'Apartments', 'Maisonettes'],
    areas: ['Zejtun', 'Zabbar', 'Fgura', 'Paola'],
  },
  {
    id: 'South East',
    name: 'South East',
    description: 'Charming fishing villages and harbors with stunning waterfront properties and maritime heritage.',
    advantages: ['Picturesque harbors', 'Seafood dining', 'Swimming spots', 'Historic charm'],
    disadvantages: ['Limited parking', 'Tourist influx', 'Steep terrain'],
    priceRange: '€800 - €3,500/month',
    typicalProperties: ['Waterfront apartments', 'Character homes', 'Converted boathouses'],
    areas: ['Marsaskala', 'Marsaxlokk', 'Birzebbuga'],
  },
  {
    id: 'Gozo',
    name: 'Gozo',
    description: 'Malta\'s sister island offers a slower pace, unspoiled landscapes, and exceptional tranquility.',
    advantages: ['Peaceful lifestyle', 'Natural beauty', 'Lower prices', 'Strong community'],
    disadvantages: ['Ferry dependency', 'Limited services', 'Distance to Malta'],
    priceRange: '€500 - €2,000/month',
    typicalProperties: ['Farmhouses', 'Character homes', 'Village apartments'],
    areas: ['Victoria', 'Xlendi', 'Marsalforn', 'Sannat', 'Gharb'],
  },
]

export const agents: Agent[] = [
  {
    id: '2906',
    name: '2906 Real Estate',
    role: 'Agents Collective · Malta',
    image: '',
    phone: '+356 9999 0001',
    whatsapp: '+35699990001',
    email: 'info@2906realestate.mt',
  },
]

export const featuredProperties: Property[] = [
  {
    id: '1',
    title: 'Stunning Seafront Penthouse',
    slug: 'stunning-seafront-penthouse-sliema',
    price: 4500,
    priceType: 'month',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    propertyType: 'Penthouses',
    category: 'aesthetics',
    region: 'Central East',
    location: 'Sliema',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80'],
    description: 'Exceptional penthouse with panoramic sea views, featuring a large terrace and premium finishes throughout.',
    features: ['Sea Views', 'Private Terrace', 'Air Conditioning', 'Parking', 'Furnished'],
    featured: true,
  },
  {
    id: '2',
    title: 'Modern St Julian\'s Apartment',
    slug: 'modern-st-julians-apartment',
    price: 2800,
    priceType: 'month',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    propertyType: 'Apartments',
    category: 'aesthetics',
    region: 'Central East',
    location: 'St. Julians',
    status: 'viewings',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
    description: 'Beautifully designed apartment in the heart of St Julian\'s, walking distance to all amenities.',
    features: ['Modern Design', 'Open Plan', 'Air Conditioning', 'Communal Pool'],
    featured: true,
  },
  {
    id: '3',
    title: 'Charming Valletta Townhouse',
    slug: 'charming-valletta-townhouse',
    price: 850000,
    priceType: 'total',
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    propertyType: 'Townhouses',
    category: 'sales',
    region: 'Central East',
    location: 'Valletta',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=800&q=80'],
    description: 'Historic townhouse in UNESCO World Heritage Valletta, lovingly restored with modern amenities.',
    features: ['Historic Character', 'Roof Terrace', 'Restored', 'Central Location'],
    featured: true,
  },
  {
    id: '4',
    title: 'Prime Office Space',
    slug: 'prime-office-space-sliema',
    price: 3500,
    priceType: 'month',
    bedrooms: 0,
    bathrooms: 2,
    area: 200,
    propertyType: 'Block',
    category: 'commercial',
    region: 'Central East',
    location: 'Sliema',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80'],
    description: 'Modern office space in a prestigious Sliema location, perfect for growing businesses.',
    features: ['Open Plan', 'Meeting Rooms', 'Parking', 'Reception Area'],
    featured: true,
  },
  {
    id: '5',
    title: 'Elegant Madliena Villa',
    slug: 'elegant-madliena-villa',
    price: 3800,
    priceType: 'month',
    bedrooms: 4,
    bathrooms: 3,
    area: 300,
    propertyType: 'Detached Villa',
    category: 'aesthetics',
    region: 'Central East',
    location: 'Madliena',
    status: 'rented',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'],
    description: 'Luxurious detached villa with private pool and garden in the exclusive Madliena area.',
    features: ['Private Pool', 'Garden', 'Garage', 'Sea Views', 'Modern Kitchen'],
    featured: true,
  },
  {
    id: '6',
    title: 'Cozy Gzira Apartment',
    slug: 'cozy-gzira-apartment',
    price: 1200,
    priceType: 'month',
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    propertyType: 'Apartments',
    category: 'letting',
    region: 'Central West',
    location: 'Gzira',
    status: 'available',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80'],
    description: 'Well-maintained apartment in Gzira, ideal for young professionals or couples.',
    features: ['Balcony', 'Air Conditioning', 'Furnished', 'Near Promenade'],
    featured: true,
  },
]
